#ifndef IMAGERENDERWORKER_H
#define IMAGERENDERWORKER_H

#include <QObject>
#include <QImage>
#include <QVector>
#include <QByteArray>
#include <QAtomicInteger>
#include <QtGlobal>
#include "data/imagedata.h"


// RenderRequest owns a deep copy of the frame bytes (avoids dangling pointers).
struct RenderRequest
{
	QByteArray frameBytes;		// Raw frame bytes

	int width;					// Frame width
	int height;					// Frame height
	EnviDataType dataType;		// Pixel type

	// Range control
	bool useAutoRange;			// true => autorange (min/max or percentile)
	bool usePercentile;			// true => percentile autorange, else min/max
	double manualMin;			// Used only when useAutoRange == false
	double manualMax;			// Used only when useAutoRange == false

	// Identity (latest-only filtering and cancellation)
	quint64 requestId;			// Monotonic id generated by caller
};

Q_DECLARE_METATYPE(RenderRequest)

class ImageRenderWorker : public QObject
{
	Q_OBJECT

public:
	explicit ImageRenderWorker(QObject* parent = nullptr);

	// Share a pointer to the viewer's latestRequestId for cooperative cancellation.
	void setLatestRequestIdSource(const QAtomicInteger<quint64>* src);

signals:
	// Event: a frame has been rendered (or cancelled) on the worker thread.
	void frameRendered(const QImage& image, quint64 requestId);

public slots:
	// Action: perform the heavy work off the GUI thread.
	void renderFrame(const RenderRequest& req);

private:
	// ---- Templated helpers (typed processing) ----
	template<typename T>
	void minMaxTyped(const T* data, int count, double& outMin, double& outMax, quint64 curId) const;

	template<typename T>
	void percentileBoundsTyped(const T* data, int count, double lowP, double highP, double& outLow, double& outHigh, quint64 curId) const;

	template<typename T>
	void scaleToU8Typed(const T* src, int count, double minV, double maxV, uchar* dst, quint64 curId) const;

	// Dispatcher: convert EnviDataType to T* once and call a functor.
	template <typename Fn>
	bool dispatchByType(EnviDataType dt, const void* ptr, int count, const Fn& fn) const;

	// Cancellation helpers
	inline bool isCancelled(quint64 curId) const
	{
		return (this->latestIdSource != nullptr) && (this->latestIdSource->loadAcquire() != curId);
	}
	inline bool isCancelledPeriodic(quint64 curId, int i) const
	{
		// Check cancellation every ~8192 items to reduce overhead.
		return ((i & 0x1FFF) == 0) && isCancelled(curId);
	}

	// Shared atomic from viewer (not owned)
	const QAtomicInteger<quint64>* latestIdSource = nullptr;
};

#endif // IMAGERENDERWORKER_H
